# Generated by Django 5.2.4 on 2025-08-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.IntegerField(default=1),
        ),
    ]
